export enum DocumentType {
    BUSINESS_SUMMARY_FILING_HISTORY = 'BUSINESS_SUMMARY_FILING_HISTORY',
    CERTIFICATE_OF_GOOD_STANDING = 'CERTIFICATE_OF_GOOD_STANDING',
    CERTIFICATE_OF_STATUS = 'CERTIFICATE_OF_STATUS',
    LETTER_UNDER_SEAL = 'LETTER_UNDER_SEAL'
  }