"""user_search_tracking

Revision ID: f01f4a22bb30
Revises: e2a1d252393b
Create Date: 2023-09-25 11:37:01.483117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f01f4a22bb30'
down_revision = 'e2a1d252393b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_history_search_date'), ['search_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_history_submitter_id'), ['submitter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_submitter_id'))
        batch_op.drop_index(batch_op.f('ix_search_history_search_date'))

    op.drop_table('search_history')
    # ### end Alembic commands ###
