"""empty message

Revision ID: ba147afab82d
Revises: 731f235afff6
Create Date: 2023-09-01 10:23:10.617405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba147afab82d'
down_revision = '731f235afff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_last_update', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.drop_column('event_last_update')

    # ### end Alembic commands ###
