"""empty message

Revision ID: 33a189aea529
Revises: c8ee6bee0f3d
Create Date: 2024-05-10 16:02:47.012268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '33a189aea529'
down_revision = 'c8ee6bee0f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    access_level = postgresql.ENUM('PUBLIC', 'LIMITED', 'EXTENDED', name='searchaccesslevel')
    access_level.create(op.get_bind())

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitter_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('access_level', access_level, nullable=True))
        batch_op.create_index(batch_op.f('ix_search_history_access_level'), ['access_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_history_submitter_account_id'), ['submitter_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_submitter_account_id'))
        batch_op.drop_index(batch_op.f('ix_search_history_access_level'))
        batch_op.drop_column('access_level')
        batch_op.drop_column('submitter_account_id')

    # ### end Alembic commands ###
