"""empty message

Revision ID: 6505125e28f1
Revises: 
Create Date: 2023-03-17 16:21:12.483532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6505125e28f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=True),
    sa.Column('firstname', sa.String(length=1000), nullable=True),
    sa.Column('lastname', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('login_source', sa.String(length=200), nullable=True),
    sa.Column('idp_userid', sa.String(length=256), nullable=True),
    sa.Column('sub', sa.String(length=36), nullable=True),
    sa.Column('iss', sa.String(length=1024), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_idp_userid'), ['idp_userid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('bor_solr_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bor_solr_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bor_solr_docs_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_bor_solr_docs_submission_date'), ['submission_date'], unique=False)

    op.create_table('solr_doc_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_status', sa.Enum('COMPLETE', 'ERROR', 'PENDING', name='solrdoceventstatus'), nullable=True),
    sa.Column('event_type', sa.Enum('RESYNC', 'UPDATE', name='solrdoceventtype'), nullable=False),
    sa.Column('solr_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solr_doc_id'], ['bor_solr_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solr_doc_events_solr_doc_id'), ['solr_doc_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solr_doc_events_solr_doc_id'))

    op.drop_table('solr_doc_events')
    with op.batch_alter_table('bor_solr_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bor_solr_docs_submission_date'))
        batch_op.drop_index(batch_op.f('ix_bor_solr_docs_identifier'))

    op.drop_table('bor_solr_docs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_idp_userid'))

    op.drop_table('users')
    # ### end Alembic commands ###
