"""empty message

Revision ID: 731f235afff6
Revises: d715d06bf96e
Create Date: 2023-07-06 11:17:16.517184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731f235afff6'
down_revision = 'd715d06bf96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bor_solr_docs', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bor_solr_docs', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
