"""empty message

Revision ID: d5b79b56a0a6
Revises: 6505125e28f1
Create Date: 2023-06-09 14:00:42.164660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b79b56a0a6'
down_revision = '6505125e28f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bor_solr_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.String(length=10), nullable=False))
        batch_op.drop_index('ix_bor_solr_docs_identifier')
        batch_op.create_index(batch_op.f('ix_bor_solr_docs_entity_id'), ['entity_id'], unique=False)
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bor_solr_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_bor_solr_docs_entity_id'))
        batch_op.create_index('ix_bor_solr_docs_identifier', ['identifier'], unique=False)
        batch_op.drop_column('entity_id')

    # ### end Alembic commands ###
