"""empty message

Revision ID: d715d06bf96e
Revises: d5b79b56a0a6
Create Date: 2023-06-15 16:46:58.127151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd715d06bf96e'
down_revision = 'd5b79b56a0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bor_solr_synonym_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synonym', sa.String(length=250), nullable=False),
    sa.Column('synonym_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synonym_type', sa.Enum('ADDRESS', 'NAME', name='solrsynonymtype'), nullable=True),
    sa.Column('last_update_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('bor_solr_synonym_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bor_solr_synonym_lists_synonym'), ['synonym'], unique=False)
        batch_op.create_index(batch_op.f('ix_bor_solr_synonym_lists_synonym_type'), ['synonym_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bor_solr_synonym_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bor_solr_synonym_lists_synonym'))
        batch_op.drop_index(batch_op.f('ix_bor_solr_synonym_lists_synonym_type'))

    op.drop_table('bor_solr_synonym_lists')
    # ### end Alembic commands ###
