"""empty message

Revision ID: e2a1d252393b
Revises: ba147afab82d
Create Date: 2023-09-01 15:20:51.753117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a1d252393b'
down_revision = 'ba147afab82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solr_doc_events_event_status'), ['event_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solr_doc_events_event_status'))

    # ### end Alembic commands ###
