apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: preload-job-template
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: search-solr-preload
      namespace: cc892f-${ENV}
    spec:
      template:
        metadata:
          name: search-solr-preload-${ENV}
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - cd /opt/app-root; ./run.sh
              env:
                - name: ORACLE_USER
                  valueFrom:
                    secretKeyRef:
                      key: ORACLE_USER
                      name: search-solr-importer-${ENV}-secret
                - name: ORACLE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: ORACLE_PASSWORD
                      name: search-solr-importer-${ENV}-secret
                - name: ORACLE_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      key: ORACLE_DB_NAME
                      name: search-solr-importer-${ENV}-secret
                - name: ORACLE_HOST
                  valueFrom:
                    secretKeyRef:
                      key: ORACLE_HOST
                      name: search-solr-importer-${ENV}-secret
                - name: ORACLE_PORT
                  valueFrom:
                    secretKeyRef:
                      key: ORACLE_PORT
                      name: search-solr-importer-${ENV}-secret
                - name: DATABASE_HOST
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_HOST
                      name: search-solr-importer-${ENV}-secret
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_NAME
                      name: search-solr-importer-${ENV}-secret
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_PASSWORD
                      name: search-solr-importer-${ENV}-secret
                - name: DATABASE_PORT
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_PORT
                      name: search-solr-importer-${ENV}-secret
                - name: DATABASE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_USERNAME
                      name: search-solr-importer-${ENV}-secret
                - name: POD_NAMESPACE
                  valueFrom:
                    secretKeyRef:
                      key: POD_NAMESPACE
                      name: search-solr-importer-${ENV}-secret
                - name: SOLR_SVC_URL
                  valueFrom:
                    secretKeyRef:
                      key: SOLR_SVC_PRELOAD_URL
                      name: search-solr-importer-${ENV}-secret
                - name: SOLR_BATCH_UPDATE_SIZE
                  valueFrom:
                    secretKeyRef:
                      key: SOLR_BATCH_UPDATE_SIZE
                      name: search-solr-importer-${ENV}-secret
                - name: REINDEX_CORE
                  value: "True"
                - name: PRELOADER_JOB
                  value: "True"
                - name: FLASK_ENV
                  valueFrom:
                    secretKeyRef:
                      key: FLASK_ENV
                      name: search-solr-importer-${ENV}-secret
              image: image-registry.openshift-image-registry.svc:5000/cc892f-tools/search-solr-importer:${ENV}
              imagePullPolicy: Always
              name: search-solr-preload-${ENV}
              resources:
                limits:
                  cpu: 250m
                  memory: 5Gi
                requests:
                  cpu: 150m
                  memory: 3Gi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 3
parameters:
  - description: Environment job will be created in
    name: ENV
    required: true
