# Copyright © 2023 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Tests to assure the Solr Services."""
from bor_api.services.bor_solr.doc_models import Address, EntityRole, DateRange

from .solr_helpers import create_entity


TEST_BUSINESSES = [
    create_entity(name='test 1234', bn='BN00012334', email='abcd@email.com', entity_id='CP1234567', legal_type='CP', entity_type='BUSINESS', state='ACTIVE'),
    create_entity(name='tester 1111', bn='09876K', email='xyz@email.com', entity_id='CP0234567', legal_type='CP', entity_type='BUSINESS', state='HISTORICAL'),
    create_entity(name='tests 2222', bn='BN00012334', email='5555@email.com', entity_id='CP0034567', legal_type='CP', entity_type='BUSINESS', state='ACTIVE'),
    create_entity(name='test 3333', bn='00987766800988', email='6666@email.com', entity_id='BC0004567', legal_type='BEN', entity_type='BUSINESS', state='ACTIVE'),
    create_entity(name='4444 test', bn='BN9000776557', entity_id='BC0000567', legal_type='BEN', entity_type='BUSINESS', state='HISTORICAL'),
    create_entity(name='single', bn='242217', entity_id='BC0000067', legal_type='BEN', entity_type='BUSINESS', state='ACTIVE'),
    create_entity(name='lots of words in here', bn='124221', entity_id='BC0000007', legal_type='BEN', entity_type='BUSINESS', state='ACTIVE'),
    create_entity(name='NOt Case SENSitive', bn='1255323221', entity_id='BC0020047', legal_type='BEN', entity_type='BUSINESS', state='ACTIVE')
]

TEST_PERSONS = [
    create_entity(name='person one',
                  entity_id='LEAR1',
                  roles=[EntityRole(id='LEAR1/roles0',
                                    relatedBN=TEST_BUSINESSES[0].bn,
                                    relatedEmail=TEST_BUSINESSES[0].email,
                                    relatedEntityType='BUSINESS',
                                    relatedIdentifier=TEST_BUSINESSES[0].identifier,
                                    relatedLegalType=TEST_BUSINESSES[0].legalType,
                                    relatedName=TEST_BUSINESSES[0].legalName,
                                    relatedState=TEST_BUSINESSES[0].state,
                                    roleType='DIRECTOR',
                                    roleDates=[DateRange(start='2020-08-04T00:03:54Z', end=None)])],
                  addresses=[Address(addressCity='Victoria',
                                     addressCountry='Canada',
                                     addressRegion='BC',
                                     addressType='DELIVERY',
                                     streetAddress='walaby way 1112',
                                     postalCode='T3S 1E4')]),
    create_entity(name='persons two',
                  entity_id='LEAR2',
                  roles=[EntityRole(id='LEAR2/roles0',
                                    relatedBN=TEST_BUSINESSES[0].bn,
                                    relatedEmail=TEST_BUSINESSES[0].email,
                                    relatedEntityType='BUSINESS',
                                    relatedIdentifier=TEST_BUSINESSES[0].identifier,
                                    relatedLegalType=TEST_BUSINESSES[0].legalType,
                                    relatedName=TEST_BUSINESSES[0].legalName,
                                    relatedState=TEST_BUSINESSES[0].state,
                                    roleType='DIRECTOR',
                                    roleDates=[DateRange(start='2019-08-04T00:03:54Z', end=None)])],
                  addresses=[Address(addressCity='Victoria',
                                     addressCountry='Canada',
                                     addressRegion='BC',
                                     addressType='DELIVERY',
                                     streetAddress='charles place 4W2',
                                     postalCode='T3R 43R')]),
    create_entity(name='personing three shoot',
                  entity_id='LEAR3',
                  roles=[EntityRole(id='LEAR3/roles0',
                                    relatedBN=TEST_BUSINESSES[0].bn,
                                    relatedEmail=TEST_BUSINESSES[0].email,
                                    relatedEntityType='BUSINESS',
                                    relatedIdentifier=TEST_BUSINESSES[0].identifier,
                                    relatedLegalType=TEST_BUSINESSES[0].legalType,
                                    relatedName=TEST_BUSINESSES[0].legalName,
                                    relatedState=TEST_BUSINESSES[0].state,
                                    roleType='DIRECTOR',
                                    roleDates=[DateRange(start='2018-08-04T00:03:54Z', end=None)])],
                  addresses=[Address(addressCity='Seattle',
                                     addressCountry='United States',
                                     addressRegion='WA',
                                     addressType='DELIVERY',
                                     streetAddress='jerry lane 9002',
                                     postalCode='V3R 4E4')]),
    create_entity(name='person-four',
                  entity_id='LEAR4',
                  roles=[EntityRole(id='LEAR4/roles0',
                                    relatedBN=TEST_BUSINESSES[1].bn,
                                    relatedEmail=TEST_BUSINESSES[1].email,
                                    relatedEntityType='BUSINESS',
                                    relatedIdentifier=TEST_BUSINESSES[1].identifier,
                                    relatedLegalType=TEST_BUSINESSES[1].legalType,
                                    relatedName=TEST_BUSINESSES[1].legalName,
                                    relatedState=TEST_BUSINESSES[1].state,
                                    roleType='DIRECTOR',
                                    roleDates=[DateRange(start='2021-08-04T00:03:54Z', end=None)])],
                  addresses=[Address(addressCity='Victoria',
                                     addressCountry='Canada',
                                     addressRegion='BC',
                                     addressType='DELIVERY',
                                     streetAddress='lala lane 9002',
                                     postalCode='V3R 4E4')]),
    create_entity(name='person and 5',
                  entity_id='LEAR5',
                  roles=[EntityRole(id='LEAR5/roles0',
                                    relatedBN=TEST_BUSINESSES[1].bn,
                                    relatedEmail=TEST_BUSINESSES[1].email,
                                    relatedEntityType='BUSINESS',
                                    relatedIdentifier=TEST_BUSINESSES[1].identifier,
                                    relatedLegalType=TEST_BUSINESSES[1].legalType,
                                    relatedName=TEST_BUSINESSES[1].legalName,
                                    relatedState=TEST_BUSINESSES[1].state,
                                    roleType='DIRECTOR',
                                    roleDates=[DateRange(start='2021-08-04T00:03:54Z', end=None)])],
                  addresses=[Address(addressCity='Victoria',
                                     addressCountry='Canada',
                                     addressRegion='BC',
                                     addressType='DELIVERY',
                                     streetAddress='hello world 9002',
                                     postalCode='V3R 1A4')]),
    create_entity(name='person&six',
                  entity_id='LEAR6',
                  roles=[EntityRole(id='LEAR6/roles0',
                                    relatedBN=TEST_BUSINESSES[1].bn,
                                    relatedEmail=TEST_BUSINESSES[1].email,
                                    relatedEntityType='BUSINESS',
                                    relatedIdentifier=TEST_BUSINESSES[1].identifier,
                                    relatedLegalType=TEST_BUSINESSES[1].legalType,
                                    relatedName=TEST_BUSINESSES[1].legalName,
                                    relatedState=TEST_BUSINESSES[1].state,
                                    roleType='DIRECTOR',
                                    roleDates=[DateRange(start='2021-08-04T00:03:54Z', end=None)])],
                  addresses=[Address(addressCity='Victoria',
                                     addressCountry='Canada',
                                     addressRegion='BC',
                                     addressType='DELIVERY',
                                     streetAddress='hello world 9002',
                                     postalCode='V3R 1A4')]),
    create_entity(name='person+seven',
                  entity_id='LEAR7',
                  roles=[EntityRole(id='LEAR7/roles0',
                                    relatedBN=TEST_BUSINESSES[1].bn,
                                    relatedEmail=TEST_BUSINESSES[1].email,
                                    relatedEntityType='BUSINESS',
                                    relatedIdentifier=TEST_BUSINESSES[1].identifier,
                                    relatedLegalType=TEST_BUSINESSES[1].legalType,
                                    relatedName=TEST_BUSINESSES[1].legalName,
                                    relatedState=TEST_BUSINESSES[1].state,
                                    roleType='DIRECTOR',
                                    roleDates=[DateRange(start='2021-08-04T00:03:54Z', end=None)])],
                  addresses=[Address(addressCity='Victoria',
                                     addressCountry='Canada',
                                     addressRegion='BC',
                                     addressType='DELIVERY',
                                     streetAddress='hello world 9002',
                                     postalCode='V3R 1A4')]),
    create_entity(name='person eight',
                  entity_id='LEAR8',
                  roles=[EntityRole(id='LEAR8/roles0',
                                    relatedBN=TEST_BUSINESSES[2].bn,
                                    relatedEmail=TEST_BUSINESSES[2].email,
                                    relatedEntityType='BUSINESS',
                                    relatedIdentifier=TEST_BUSINESSES[2].identifier,
                                    relatedLegalType=TEST_BUSINESSES[2].legalType,
                                    relatedName=TEST_BUSINESSES[2].legalName,
                                    relatedState=TEST_BUSINESSES[2].state,
                                    roleType='DIRECTOR',
                                    roleDates=[DateRange(start='2015-08-04T00:03:54Z', end='2016-08-04T00:03:54Z')])],
                  addresses=[Address(addressCity='Victoria',
                                     addressCountry='Canada',
                                     addressRegion='BC',
                                     addressType='DELIVERY',
                                     streetAddress='hello world 9002',
                                     postalCode='V3R 1A4')]),
]
    
SOLR_TEST_DOCS = TEST_BUSINESSES + TEST_PERSONS
