# Copyright © 2025 Province of British Columbia
#
# Licensed under the BSD 3 Clause License, (the "License");
# you may not use this file except in compliance with the License.
# The template for the license can be found here
#    https://opensource.org/license/bsd-3-clause/
#
# Redistribution and use in source and binary forms,
# with or without modification, are permitted provided that the
# following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS”
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: search-updater-pipeline
description: Deployment pipeline
serialPipeline:
 stages:
 - targetId: k973yf-dev
   profiles: [dev]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "development"
      deploy-project-id: "k973yf-dev"
      service-name: "search-solr-updater-dev"
      container-name: "search-solr-updater-dev"
      service-account: "sa-api@k973yf-dev.iam.gserviceaccount.com"
 - targetId: k973yf-test
   profiles: [test]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "development"
      deploy-project-id: "k973yf-test"
      service-name: "search-solr-updater-test"
      container-name: "search-solr-updater-test"
      service-account: "sa-api@k973yf-test.iam.gserviceaccount.com"
 - targetId: k973yf-integration
   profiles: [sandbox]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "sandbox"
      deploy-project-id: "k973yf-integration"
      service-name: "search-solr-updater-sandbox"
      container-name: "search-solr-updater-sandbox"
      service-account: "sa-api@k973yf-integration.iam.gserviceaccount.com"
 - targetId: k973yf-prod
   profiles: [prod]
   strategy:
    standard:
      verify: false
   deployParameters:
   - values:
      deploy-env: "production"
      deploy-project-id: "k973yf-prod"
      service-name: "search-solr-updater-prod"
      container-name: "search-solr-updater-prod"
      container-concurrency: "60"
      resources-cpu: "8000m"
      resources-memory: "4Gi"
      service-account: "sa-api@k973yf-prod.iam.gserviceaccount.com"
      max-scale: "10"