export enum AccountStatusE {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  NSF_SUSPENDED = 'NSF_SUSPENDED',
  PENDING_STAFF_REVIEW = 'PENDING_STAFF_REVIEW',
  PENDING_ACTIVATION = 'PENDING_ACTIVATION',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED'
}
