export enum ErrorCodeE {
  ACCOUNT_IN_PAD_CONFIRMATION_PERIOD = 'ACCOUNT_IN_PAD_CONFIRMATION_PERIOD',
  ACCOUNT_SETUP_ERROR = 'ACCOUNT_SETUP_ERROR',
  AUTH_ROLES_ERROR = 'AUTH_ROLES_ERROR',
  AUTH_PRODUCTS_ERROR = 'AUTH_PRODUCTS_ERROR',
  BCOL_ACCOUNT_CLOSED = 'BCOL_ACCOUNT_CLOSED',
  BCOL_ACCOUNT_REVOKED = 'BCOL_ACCOUNT_REVOKED',
  BCOL_ACCOUNT_INSUFFICIENT_FUNDS = 'BCOL_ACCOUNT_INSUFFICIENT_FUNDS',
  BCOL_ERROR = 'BCOL_ERROR',
  BCOL_INVALID_ACCOUNT = 'BCOL_INVALID_ACCOUNT',
  BCOL_UNAVAILABLE = 'BCOL_UNAVAILABLE',
  BCOL_USER_REVOKED = 'BCOL_USER_REVOKED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
}
