export enum RoleTypeE {
  COMPLETING_PARTY = 'COMPLETING PARTY',
  DIRECTOR = 'DIRECTOR',
  INCORPORATOR = 'INCORPORATOR',
  PARTNER = 'PARTNER',
  SIGNIFICANT_INDIVIDUAL = 'SIGNIFICANT INDIVIDUAL'
}
