name: Search Updater CI

on:
  pull_request:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "queue-services/search-solr-updater/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./queue-services/search-solr-updater

jobs:
  search-updater-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "search-solr-updater"
      working_directory: "./queue-services/search-solr-updater"
      codecov_flag: "search-solr-updater"

