name: REGISTRIES SEARCH FLOW TEST

on: [workflow_dispatch]

defaults:
  run:
    shell: bash
    working-directory: ./integration-test-scripts

jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run k6 flow test in TEST env
        uses: grafana/k6-action@v0.2.0
        with:
          filename: integration-test-scripts/search_full_flow.js
          flags: --vus 2 --duration 1m
        env:
          realm: ${{ secrets.REALM }}
          client_id: ${{ secrets.TEST_CLIENT_ID }}
          client_secret: ${{ secrets.TEST_CLIENT_SECRET }}
          account_id: ${{ secrets.TEST_ACCOUNT_ID }}
          api_key: ${{ secrets.TEST_API_KEY }}
