name: Search Solr Importer CI

on:
  pull_request:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "search-solr-importer/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./search-solr-importer

jobs:
  search-solr-importer-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "search-solr-importer"
      working_directory: "./search-solr-importer"
      codecov_flag: "search-solr-importer"
