name: REGISTRIES SEARCH UI CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "search-ui/**"

defaults:
  run:
    shell: bash
    working-directory: ./search-ui

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    if: github.repository == 'bcgov/registries-search'

    steps:
      - uses: actions/checkout@v4
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  unit-testing:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test:unit

  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
