"""empty message

Revision ID: 065057716b7a
Revises: 34c72e8a1cb2
Create Date: 2022-07-05 13:42:11.075880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065057716b7a'
down_revision = '34c72e8a1cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_access_request', sa.Column('business_name', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_access_request', 'business_name')
    # ### end Alembic commands ###
