"""empty message

Revision ID: 0ba810e98e41
Revises: eaf25b9a20bf
Create Date: 2024-11-05 16:40:24.716461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba810e98e41'
down_revision = 'eaf25b9a20bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_access_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_access_request_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_access_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_access_request_payment_id'))

    # ### end Alembic commands ###
