"""empty message

Revision ID: eaf25b9a20bf
Revises: c10f3d4b2262
Create Date: 2024-07-23 13:12:59.736684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf25b9a20bf'
down_revision = 'c10f3d4b2262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_last_update', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_user_idp_userid')
        batch_op.drop_constraint('users_idp_userid_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_idp_userid'), ['idp_userid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_idp_userid'))
        batch_op.create_unique_constraint('users_idp_userid_key', ['idp_userid'])
        batch_op.create_index('ix_user_idp_userid', ['idp_userid'], unique=True)

    with op.batch_alter_table('solr_doc_events', schema=None) as batch_op:
        batch_op.drop_column('event_last_update')

    # ### end Alembic commands ###
