"""empty message

Revision ID: 34c72e8a1cb2
Revises: be013c507d76
Create Date: 2022-06-14 14:16:08.752741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c72e8a1cb2'
down_revision = 'be013c507d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'file_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('file_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
