"""login_source

Revision ID: 6072ec70fb7a
Revises: 34c72e8a1cb2
Create Date: 2022-07-05 13:42:11.075880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6072ec70fb7a'
down_revision = '065057716b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_source', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_source')
    # ### end Alembic commands ###
