"""Solr tracking tables

Revision ID: c10f3d4b2262
Revises: 3faf50891480
Create Date: 2022-12-19 13:19:59.682675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c10f3d4b2262'
down_revision = '3faf50891480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solr_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('identifier', sa.String(length=10), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solr_docs_identifier'), 'solr_docs', ['identifier'], unique=False)
    op.create_index(op.f('ix_solr_docs_submission_date'), 'solr_docs', ['submission_date'], unique=False)
    op.create_table('solr_doc_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_status', sa.Enum('COMPLETE', 'ERROR', 'PENDING', name='solrdoceventstatus'), nullable=True),
    sa.Column('event_type', sa.Enum('RESYNC', 'UPDATE', name='solrdoceventtype'), nullable=False),
    sa.Column('solr_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['solr_doc_id'], ['solr_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solr_doc_events_solr_doc_id'), 'solr_doc_events', ['solr_doc_id'], unique=False)
    # ### end Alembic commands ###
    op.drop_constraint('users_sub_key', 'users', type_='unique')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solr_doc_events_solr_doc_id'), table_name='solr_doc_events')
    op.drop_table('solr_doc_events')
    op.drop_index(op.f('ix_solr_docs_submission_date'), table_name='solr_docs')
    op.drop_index(op.f('ix_solr_docs_identifier'), table_name='solr_docs')
    op.drop_table('solr_docs')
    # ### end Alembic commands ###
    op.execute('DROP TYPE solrdoceventstatus')
    op.execute('DROP TYPE solrdoceventtype')
    op.create_unique_constraint('users_sub_key', 'users', ['sub'])
