"""add_idp_userid_to_users

Revision ID: f7d39c77458f
Revises: 065057716b7a
Create Date: 2022-11-23 13:40:35.452492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d39c77458f'
down_revision = '6072ec70fb7a'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('idp_userid', sa.String(length=256)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'idp_userid')
    # ### end Alembic commands ###
